import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connaisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt="image"
            src="/static/hero-image-F.png"
            width={700}
            height={400}
          />
          <div className={styles.cardLayout}>
            <Card
              name="DarkHouse Coffee"
              imgUrl="/static/hero-image.png"
              href="/coffee-store/darkhouse-coffee"
              className={styles.card}
            />
            <Card
              name="DarkHouse Coffee"
              imgUrl="/static/hero-image.png"
              href="/coffee-store/darkhouse-coffee"
              className={styles.card}
            />
            <Card
              name="DarkHouse Coffee"
              imgUrl="/static/hero-image.png"
              href="/coffee-store/darkhouse-coffee"
              className={styles.card}
            />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
